name: residex_app
description: "Malaysian super residential app."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.10.0

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  # State Management & Navigation
  flutter_riverpod: ^3.1.0
  riverpod_annotation: ^4.0.0

   # üî• Firebase Core
  firebase_core: ^4.4.0

  # üî• Firebase Services 
  firebase_auth: ^6.1.4
  firebase_storage: ^13.0.6
  cloud_firestore: ^6.1.2
  firebase_app_check: ^0.4.1+4

  # üîê Google Sign In
  google_sign_in: ^6.2.2

  # Local Database
  drift: ^2.18.0
  sqlite3_flutter_libs: ^0.5.24
  path_provider: ^2.1.3
  path: ^1.9.0

  # Navigation
  go_router: ^14.2.0  
  
  # Camera & Image
  camera: ^0.11.0
  image_picker: ^1.0.7
  
  # UI & Animations
  flutter_animate: ^4.5.2
  google_fonts: ^6.3.2
  cupertino_icons: ^1.0.8
  lucide_icons: ^0.257.0
  
  # Storage & Utils
  file_picker: ^8.1.2
  flutter_contacts: ^1.1.7+1
  permission_handler: ^11.0.1
  shared_preferences: ^2.2.2
  intl: ^0.20.2
  uuid: ^4.2.2
  google_generative_ai: ^0.4.6 
  sensors_plus: ^5.0.1       # Magnetometer readings (Layer 1)
  vibration: ^2.0.0   
  network_info_plus: ^6.0.0  # Wi-Fi SSID + IP info (Layer 3)

  equatable: ^2.0.5
  dartz: ^0.10.1
  device_info_plus: ^10.1.0
  smooth_page_indicator: ^1.1.0

  flutter_svg: ^2.0.10              # Logo & badges
  shimmer: ^3.0.0                   # Loading states
  table_calendar: ^3.1.2            # Calendar widget
  glassmorphism: ^3.0.0             # Glass effects
  animations: ^2.0.11               # Page transitions
  cached_network_image: ^3.4.1     # Image caching
  lottie: ^3.1.2                   # Complex animations (optional)
  confetti: ^0.7.0                 # Achievement unlocks (optional)

dev_dependencies:
# Code generation
  build_runner: ^2.4.9
  drift_dev: ^2.18.0
  riverpod_generator: ^4.0.0+1

  # Testing
  mockito: ^5.4.4

  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    # Food categories
    - assets/photos/Food/Coffee/
    - assets/photos/Food/Dessert/
    - assets/photos/Food/Japanese/
    - assets/photos/Food/Korean/
    - assets/photos/Food/Mamak/
    - assets/photos/Food/Western/
    - assets/photos/Food/Chinese/
    - assets/photos/Food/Indian/
    # Other categories
    - assets/photos/Entertainment/
    - assets/photos/Sports/
    - assets/photos/Trips/
    - assets/photos/Groceries/
    - assets/photos/Shopping/
    - assets/photos/Stock/
    # Payment method logos
    - assets/logos/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
